spring.jpa.open-in-view=false
server.port=8080
use.confirmation.service=false
confirmationms.url=http://localhost:8070/

spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:testdb;MODE=LEGACY;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.properties.hibernate.id.new_generator_mappings=false
