name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [monolith, credit-service]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Build and test ${{ matrix.module }}
        working-directory: ${{ matrix.module }}
        run: ./mvnw --batch-mode clean test
